# Generated by Django 5.2.5 on 2025-09-22 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('eaten_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-eaten_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MacroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.PositiveIntegerField(default=2000)),
                ('daily_protein_g', models.PositiveIntegerField(default=150)),
                ('daily_carbs_g', models.PositiveIntegerField(default=200)),
                ('daily_fats_g', models.PositiveIntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='macro_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
